### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by Dax333** [peez80/docker-openhab#3]
I'm new to docker so please forgive my ignorance.
Here is what I'm getting when using your project.

$ docker pull peez/openhab
Using default tag: latest
latest: Pulling from peez/openhab
4d06f2521e4f: Pull complete 
4a65dbf2da0d: Pull complete 
cedcc17e2531: Pull complete 
b7680ad4fdae: Pull complete 
e659264b880c: Pull complete 
e1100aba18f5: Pull complete 
266dc82eb969: Pull complete 
3797900817c2: Pull complete 
Digest: sha256:1c4228bfbc58da29030313495dfeecf2542306e91c0bffcf3f3b054e8ec8d759
Status: Downloaded newer image for peez/openhab:latest

$ docker run -itd -v /config/dir/on/host:/opt/openhab/configurations peez/openhab
671499486cd61e0bd5c0c959c953e7693050bdb330d482069b1c06a231f21017
docker: Error response from daemon: Cannot start container 671499486cd61e0bd5c0c959c953e7693050bdb330d482069b1c06a231f21017: [9] System error: exec format error.
$ docker run -it -e debug=true peez/openhab
exec format error

**Comment by peez80** [comment]
Hi,
it's working here without a problem. From my experience errors like this are due to OS incompatibilities.
Two ideas that come across my mind:
1. Are you using a 32-bit system on your host? Haven't tried but the image should only run on 64-bit host machines.
2. Any possibility that windows line breaks came somewhere? (the docker run command at the end, to the Dockerfile if you cloned the git repository by yourself)

**Comment by Dax333** [comment]
Ahh that’s probably it.  I’m running it on a Raspberry Pi 2.

I’ll have to test it on the 64bit rpi 3 soon.
